server:
    port: 8093
season:
    datasource:
        master:
            url: jdbc:mysql://127.0.0.1:3306/admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
            username: root
            password: MySQL_1234
        slaver:
            url: jdbc:mysql://127.0.0.1:3306/admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
            username: root
            password: MySQL_1234
# Redis配置
spring:
    redis:
        host: 127.0.0.1
        port: 6379
        database: 8
        pool:
            max-active: 5000 #最大连接数
            max-idle: 50 #最大空闲连接数
            max-wait: 10000 #获取连接最大等待时间ms
    http: # 文件上传大小限制
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

logging:
    path: I:\admin\log

file:
    uploadPath: I:\admin\fileUpload\
